### ISSUE TITLE
! LaTeX Error: File `ul_p' not found.

### ISSUE THREAD

**Issue by judith-bourque** [clessn/gabaritRmd_memoireULaval#1]

**Comment by judith-bourque** [comment]
@AdriClout Je vais utiliser cet issue pour documenter le problème encontré.

**Comment by judith-bourque** [comment]
Pour utiliser ce gabarit, je me base sur le [README ](https://github.com/ismayc/thesisdown/blob/5f113346cef5d190b0a6a7aa0c2514bfad49508b/README.md) de thesisdown.

Questions
* Est-ce qu'il faut un Rproject? Si oui, où?
* Comment est-ce qu'on génère le document? ([instructions](https://github.com/ismayc/thesisdown/blob/master/README.md#rendering) dans thesisdown)

**Comment by judith-bourque** [comment]
Quand je knit index.Rmd, je reçois le message d'erreur suivant
```
output file: Memoire_PrénomNom.knit.md

! LaTeX Error: File `ul_p' not found.

Error: LaTeX failed to compile Memoire_PrénomNom.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See Memoire_PrénomNom.log for more info.
Execution halted
```

Voici ce que j'ai essayé:
* Télécharger les packages bookdown et thesisdown
* MAJ tous mes packages
* Suivre toutes les étapes du [site](https://yihui.org/tinytex/r/#debugging) indiqué dans le message d'erreur
* Redémarrer ma session
* Créer un RProject au niveau de mon repository ET du dossier index
* Googler mon message d'erreur

**Comment by judith-bourque** [comment]
Voici comment j'ai réussi à produire le PDF avec le bon contenu

1. Knit `index.Rmd` et reçu le message d'erreur suivant
```
output file: Memoire_PrénomNom.knit.md

! LaTeX Error: File `ul_p' not found.

Error: LaTeX failed to compile Memoire_PrénomNom.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See Memoire_PrénomNom.log for more info.
Execution halted
```
2. Ouvert `Memoire_PrénomNom.tex` dans RStudio et sélectionné Compile PDF
3. Le PDF est généré dans le dossier index avec le bon contenu, mais les messages d'erreurs suivants apparaissent dans RStudio:

```
# 1
LaTeX Warning: You have requested document class `ulaval',
               but the document class provides `reedthesis'.

# 2
Package fixltx2e Warning: fixltx2e is not required with releases after 2015
(fixltx2e)                All fixes are now in the LaTeX kernel.
(fixltx2e)                See the latexrelease package for details.

#3 
! LaTeX Error: File `ul_p' not found.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
```

**Comment by judith-bourque** [comment]
Je suis présentement les instructions pour [installer des packages LaTeX manquants](https://bookdown.org/yihui/rmarkdown-cookbook/install-latex-pkgs.html).

Étapes

1. Créer un Rproject dans dossier index
2. Knit `index.Rmd` 
3. Ouvert `Memoire_PrénomNom.tex` dans RStudio et sélectionné Compile PDF
4. Rouler le code ` tinytex::parse_packages("Memoire_PrénomNom.log")`
Message d'erreur:
```
tlmgr search --file --global "/ul_p"
character(0)
Warning message:
In tinytex::parse_packages("Memoire_PrénomNom.log") :
  Failed to find a package that contains ul_p
```
5. Rouler le code `tinytex::parse_install("Memoire_PrénomNom.log")`
Message d'erreur
```
tlmgr search --file --global "/ul_p"
Warning message:
In parse_packages(...) : Failed to find a package that contains ul_p
```
6. Rouler les codes ci-dessous et ça donne les même messages
```
tinytex::parse_install(
    text = "! LaTeX Error: File `ul_p' not found."
)
tinytex::parse_packages(
    text = "! LaTeX Error: File `ul_p' not found."
)
```

**Comment by judith-bourque** [comment]
J'avais déjà installé MiKTeX donc c'est peut-être la source du problème.

Étapes faites dans la console MiKTeX
1. Fix le path (nécessaire selon les instructions dans la console)
2. Installer les MAJ
3.  Dans console MiKTeX, activer option `Always install missing packages on-the-fly` tel que suggéré [ici](https://github.com/rstudio/rmarkdown/issues/1285#issuecomment-374340175).

J'ai toujours le même message d'erreur.

**Comment by judith-bourque** [comment]
J'ai réussi à produire le document PDF en suivant la procédure ci-dessous:
1. Utiliser un Mac (au lieu d'un PC)
2. Installer [MacTex](https://tug.org/mactex/) (oui, c'est 5 GB...!)
3. Cloner le repository localement
5. *Knit* le fichier `index.Rmd`
6. Terminé! Le fichier PDF s'ouvre automatiquement.

NB: je n'ai pas eu recours à TinyTex:
```
tinytex::is_tinytex()
[1] FALSE
```

Quelques questions à adresser:
1. Est-ce que ce gabarit demande qu'on ait la version intégrale de LaTeX? En d'autres mots, est-ce que tiny_tex ne suffirait pas finalement?
2. Est-ce que ce gabarit fonctionne sur un PC AVEC une version intégrale de LaTeX?
3. Est-ce qu'un RProject est nécessaire pour compiler le gabarit vide? _Non. J'ai essayé avec et sans RProject et il n'y a aucune différence._
4. Est-ce que le dossier index est nécessaire pour compiler le gabarit vide? _Non. J'ai essayé avec et sans dossier index et il n'y a aucune différence._

----

Session info
```
R version 4.2.2 (2022-10-31)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Ventura 13.0

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] remotes_2.4.2

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.9            urlchecker_1.0.1      compiler_4.2.2       
 [4] later_1.3.0           profvis_0.3.7         prettyunits_1.1.1    
 [7] tools_4.2.2           pkgload_1.3.1         digest_0.6.30        
[10] pkgbuild_1.3.1        evaluate_0.18         memoise_2.0.1        
[13] lifecycle_1.0.3       rlang_1.0.6           shiny_1.7.3          
[16] cli_3.4.1             rstudioapi_0.14       curl_4.3.3           
[19] yaml_2.3.6            xfun_0.34             fastmap_1.1.0        
[22] stringr_1.4.1         withr_2.5.0           knitr_1.40           
[25] htmlwidgets_1.5.4     fs_1.5.2              devtools_2.4.5       
[28] rprojroot_2.0.3       glue_1.6.2            R6_2.5.1             
[31] processx_3.8.0        thesisdown_0.2.0.9000 rmarkdown_2.17       
[34] bookdown_0.29.3       sessioninfo_1.2.2     purrr_0.3.5          
[37] callr_3.7.3           magrittr_2.0.3        usethis_2.1.6        
[40] ps_1.7.2              promises_1.2.0.1      ellipsis_0.3.2       
[43] htmltools_0.5.3       xtable_1.8-4          mime_0.12            
[46] httpuv_1.6.6          stringi_1.7.8         miniUI_0.1.1.1       
[49] cachem_1.0.6          crayon_1.5.2  
```

**Comment by judith-bourque** [comment]
@AdriClout Peux-tu spécifier ici la source du message d'erreur `! LaTeX Error: File ul_p not found.` s.v.p.? :)

**Comment by AdriClout** [comment]
C'est réglé! Il manquait simplement le fichier ul_p.pdf, qui est le logo de l'ULaval, dans le dossier «figure». Ce logo sert à la page titre. Il était absent puisque le .gitignore ne permettait pas de le pusher en ligne. J'ai donc enlever les fichiers pdf du .gitignore, et j'ai remis le logo dans le dossier figure.
